### PR TITLE
Fix wrong typing in pybricks.parameters.Stop

### PR DESCRIPTION
**Pull request by TheVinhLuong102**
David, Laurens,

I've found some minor wrong typing info.

### CODE REVIEW

**Comment by dlech** [comment]
Thanks! Can you also add a changelog entry for this?

**Comment by TheVinhLuong102** [comment]
Yes, David, I've added a line about this in the change log. :)

**Comment by dlech** [comment]
I just pushed a commit to master that should fix the CI failures. Can you please rebase both pull requests so we can try the CI again?

**Comment by TheVinhLuong102** [comment]
great, it seems all sorted out now David :)

**Comment by dlech** [comment]
Merged, thanks!

**Comment by TheVinhLuong102** [comment]
Labor Day achievement! :D

Thanks David.

**Pull request merged**
