### PR TITLE
api: Use leading _ to hide internals in intellisense

### PR DESCRIPTION
**Pull request by dlech**
Intellisense in VS Code (both jedi and ms python language server) picks up all imported names and suggests them with equal priority for code completion. By adding a leading underscore, intellisense lists these with a lower priority, so they don't get in the way.

### CODE REVIEW

**Comment by laurensvalk** [comment]
If we're going to do this, we should probably bite the bullet and rename `builtins.py` back to `_common.py` after all.

**Comment by dlech** [comment]
> If we're going to do this, we should probably bite the bullet and rename `builtins.py` back to `_common.py` after all.

I have added a commit for this.

**Comment by laurensvalk** [comment]
Thanks, but it was mainly to avoid having it renamed thrice :smile:, so it would be great to amend or squash.

**Comment by dlech** [comment]
Oh, OK. Squashed it.

**Pull request merged**
